let b = {
  fr: {
    schedule: {
      day: "journée",
      week: "La semaine",
      workWeek: "Semaine de travail",
      month: "Mois",
      agenda: "Ordre du jour",
      weekAgenda: "Agenda de la semaine",
      workWeekAgenda: "Agenda de la semaine de travail",
      monthAgenda: "Agenda du mois",
      today: "Aujourd'hui",
      noEvents: "Pas d'événements",
      emptyContainer: "Aucun événement n'est prévu ce jour-là.",
      allDay: "Toute la journée",
      start: "Début",
      end: "Fin",
      more: "plus",
      close: "Fermer",
      cancel: "Annuler",
      noTitle: "(Pas de titre)",
      delete: "Effacer",
      deleteEvent: "Supprimer un événement",
      deleteMultipleEvent: "Supprimer plusieurs événements",
      selectedItems: "Articles sélectionnés",
      deleteSeries: "Supprimer la série",
      edit: "modifier",
      editSeries: "Modifier la série",
      editEvent: "Modifier l'événement",
      createEvent: "Créer",
      subject: "Assujettir",
      addTitle: "Ajouter un titre",
      moreDetails: "Plus de détails",
      save: "sauvegarder",
      editContent:
        "Voulez-vous modifier uniquement cet événement ou une série entière?",
      deleteRecurrenceContent:
        "Voulez-vous supprimer uniquement cet événement ou une série entière?",
      deleteContent: "Êtes-vous sûr de vouloir supprimer cet événement?",
      deleteMultipleContent:
        "Êtes-vous sûr de vouloir supprimer les événements sélectionnés?",
      newEvent: "Nouvel évènement",
      title: "Titre",
      location: "Emplacement",
      description: "La description",
      timezone: "Fuseau horaire",
      startTimezone: "Début du fuseau horaire",
      endTimezone: "Fin du fuseau horaire",
      repeat: "Répéter",
      saveButton: "sauvegarder",
      cancelButton: "Annuler",
      deleteButton: "Effacer",
      recurrence: "Récurrence",
      wrongPattern: "Le modèle de récurrence n'est pas valide.",
      seriesChangeAlert:
        "Les modifications apportées à des instances spécifiques de cette série seront annulées et ces événements correspondront à nouveau à la série.",
      createError:
        "La durée de l'événement doit être plus courte que sa fréquence. Raccourcissez la durée ou modifiez le modèle de récurrence dans l'éditeur d'événement de récurrence.",
      recurrenceDateValidation:
        "Certains mois ont moins que la date sélectionnée. Pour ces mois, l'événement se produira à la dernière date du mois.",
      sameDayAlert:
        "Deux occurrences du même événement ne peuvent pas se produire le même jour.",
      editRecurrence: "Modifier la récurrence",
      repeats: "Répète",
      alert: "Alerte",
      startEndError:
        "La date de fin sélectionnée se produit avant la date de début.",
      invalidDateError: "La valeur de date saisie est invalide.",
      ok: "D'accord",
      occurrence: "Occurrence",
      series: "Séries",
      previous: "précédent",
      next: "Prochain",
      timelineDay: "Journée chronologique",
      timelineWeek: "Semaine chronologique",
      timelineWorkWeek: "Semaine de travail chronologique",
      timelineMonth: "Mois de la chronologie",
      blockAlert: "Vous ne pouvez pas ajouter un evenement dans ce temps là",
      yes: "Oui",
      no: "Non",
      timelineYear: "Année",
      editFollowingEvent: "Modifier evenement courrant",
      deleteTitle: "Supprimer Evenement",
      editTitle: "Modifier evenement",
      beginFrom: "Commencer de",
      endAt: "Terminer à",
      expandAllDaySection: "Expander",
      collapseAllDaySection: "Collapser",
      year: "Année",
    },
    recurrenceeditor: {
      none: "Aucun",
      daily: "du quotidien",
      weekly: "Hebdomadaire",
      monthly: "Mensuel",
      month: "Mois",
      yearly: "Annuel",
      never: "Jamais",
      until: "Jusqu'à",
      count: "Compter",
      first: "Premier",
      second: "Seconde",
      third: "Troisième",
      fourth: "Quatrième",
      last: "Dernier",
      repeat: "Répéter",
      repeatEvery: "Répéter tous les",
      on: "Répéter sur",
      end: "Fin",
      onDay: "journée",
      days: "Journées)",
      weeks: "Semaines)",
      months: "Mois)",
      years: "Années)",
      every: "chaque",
      summaryTimes: "fois)",
      summaryOn: "sur",
      summaryUntil: "jusqu'à",
      summaryRepeat: "Répète",
      summaryDay: "journées)",
      summaryWeek: "semaines)",
      summaryMonth: "mois)",
      summaryYear: "années)",
      monthWeek: "Mois Semaine",
      monthPosition: "Position du mois",
      monthExpander: "Mois Expander",
      yearExpander: "Année Expander",
      repeatInterval: "Intervalle de répétition",
    },

    calendar: {
      today: "Aujourd'hui",
    },
  },
};

let a = {
  es: {
    schedule: {
      day: "Día",
      week: "Semana",
      workWeek: "Semana de trabajo",
      month: "Mes",
      year: "Año",
      agenda: "Agenda",
      weekAgenda: "Agenda de la semana",
      workWeekAgenda: "Agenda de la semana laboral",
      monthAgenda: "Agenda del mes",
      today: "Hoy",
      noEvents: "No hay eventos",
      emptyContainer: "No hay eventos programados para este día.",
      allDay: "Todo el dia",
      start: "comienzo",
      end: "Final",
      more: "más",
      close: "Cerca",
      cancel: "Cancelar",
      noTitle: "(Sin título)",
      delete: "Eliminar",
      deleteEvent: "Este evento",
      deleteMultipleEvent: "Eliminar múltiples eventos",
      selectedItems: "Artículos seleccionados",
      deleteSeries: "Serie completa",
      edit: "Editar",
      editSeries: "Serie completa",
      editEvent: "Este evento",
      createEvent: "Crear",
      subject: "Tema",
      addTitle: "Añadir título",
      moreDetails: "Más detalles",
      save: "Salvar",
      editContent: "¿Cómo le gustaría cambiar la cita en la serie?",
      deleteContent: "¿Seguro que quieres eliminar este evento?",
      deleteMultipleContent:
        "¿Estás seguro de que deseas eliminar los eventos seleccionados?",
      newEvent: "Nuevo evento",
      title: "Título",
      location: "Ubicación",
      description: "Descripción",
      timezone: "Zona horaria",
      startTimezone: "Zona horaria de inicio",
      endTimezone: "Zona horaria final",
      repeat: "Repetir",
      saveButton: "Salvar",
      cancelButton: "Cancelar",
      deleteButton: "Eliminar",
      recurrence: "Reaparición",
      wrongPattern: "El patrón de recurrencia no es válido.",
      seriesChangeAlert:
        "¿Desea cancelar los cambios realizados en instancias específicas de esta serie y volver a vincularlos con toda la serie?",
      createError:
        "La duración del evento debe ser más corta que la frecuencia con la que ocurre. Acorte la duración o cambie el patrón de recurrencia en el editor de eventos de recurrencia.",
      sameDayAlert:
        "Dos ocurrencias del mismo evento no pueden ocurrir en el mismo día.",
      editRecurrence: "Editar recurrencia",
      repeats: "Repite",
      alert: "Alerta",
      startEndError:
        "La fecha de finalización seleccionada ocurre antes de la fecha de inicio.",
      invalidDateError: "El valor de la fecha ingresada no es válido.",
      blockAlert:
        "Los eventos no se pueden programar dentro del rango de tiempo bloqueado.",
      ok: "Okay",
      yes: "si",
      no: "No",
      occurrence: "Ocurrencia",
      series: "Serie",
      previous: "Anterior",
      next: "próximo",
      timelineDay: "Día de la línea de tiempo",
      timelineWeek: "Semana de la línea de tiempo",
      timelineWorkWeek: "Semana laboral cronológica",
      timelineMonth: "Mes de la línea de tiempo",
      timelineYear: "Cronología Año",
      editFollowingEvent: "Eventos siguientes",
      deleteTitle: "Eliminar evento",
      editTitle: "Editar evento",
      beginFrom: "Comience desde",
      endAt: "Termina en",
      expandAllDaySection: "Expandir-sección-todo-el-día",
      collapseAllDaySection: "Colapsar la sección de todo el día",
    },
    recurrenceeditor: {
      none: "Ninguna",
      daily: "Diario",
      weekly: "Semanal",
      monthly: "Mensual",
      month: "Mes",
      yearly: "Anual",
      never: "Nunca",
      until: "Hasta",
      count: "Contar",
      first: "primero",
      second: "Segundo",
      third: "Tercero",
      fourth: "Cuarto",
      last: "Último",
      repeat: "Repetir",
      repeatEvery: "Repite cada",
      on: "Repetir en",
      end: "Final",
      onDay: "Día",
      days: "Dias)",
      weeks: "Semanas)",
      months: "Meses)",
      years: "Años)",
      every: "cada",
      summaryTimes: "veces)",
      summaryOn: "en",
      summaryUntil: "hasta",
      summaryRepeat: "Repite",
      summaryDay: "dias)",
      summaryWeek: "semanas)",
      summaryMonth: "meses)",
      summaryYear: "años)",
      monthWeek: "Mes Semana",
      monthPosition: "Posición del mes",
      monthExpander: "Expansor de mes",
      yearExpander: "Expansor de año",
      repeatInterval: "Intervalo de repetición",
    },
    calendar: {
      today: "Hoy",
    },
  },
};
